apiVersion: webapp.bpmf.io/v1
kind: Guestbook
metadata:
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/instance: guestbook-sample
    app.kubernetes.io/part-of: bpmf-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: bpmf-operator
  name: guestbook-sample
spec:
  # TODO(user): Add fields here
  foo: a
